client_name:
  target: dev
  outputs:
    dev:
      type: synapse
      driver: 'ODBC Driver 18 for SQL Server'
      server: your-server.database.windows.net
      port: 1433
      database: Your-Database
      schema: dbt_dev
      authentication: sql
      user: "{{ env_var('DBT_SYNAPSE_USER') }}"
      password: "{{ env_var('DBT_SYNAPSE_PASSWORD') }}"
      encrypt: true
      trust_cert: true
      retries: 1
      login_timeout: 0
      query_timeout: 0
      threads: 4

    prod:
      type: synapse
      driver: 'ODBC Driver 18 for SQL Server'
      server: your-server.database.windows.net
      port: 1433
      database: Your-Database
      schema: dbt_prod
      authentication: sql
      user: "{{ env_var('DBT_SYNAPSE_USER') }}"
      password: "{{ env_var('DBT_SYNAPSE_PASSWORD') }}"
      encrypt: true
      trust_cert: true
      retries: 1
      login_timeout: 0
      query_timeout: 0
      threads: 4