version: 2

models:
  - name: fct_sales
    description: "Sales fact table for Power BI"
    config:
      materialized: table
      
  - name: dim_customers_v2
    description: "Customer dimension for Power BI"
    config:
      materialized: table
      
  - name: dim_products_v2
    description: "Product dimension for Power BI"
    config:
      materialized: table