version: 2

sources:
  - name: fivetran_source
    database: "{{ var('fivetran_database') }}"
    schema: "{{ var('fivetran_schema') }}"
    description: "Raw data synced from Fivetran"
    
    tables:
      - name: customers
        description: "Customer data from source system"
        columns:
          - name: customer_id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: customer_name
          - name: email
          - name: created_at
          - name: _fivetran_synced
            description: "Timestamp when Fivetran synced this record"
          - name: _fivetran_deleted
            description: "Soft delete flag from Fivetran"
            
      - name: orders
        description: "Order data from source system"
        columns:
          - name: order_id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - relationships:
                  to: ref('stg_customers')
                  field: customer_id
          - name: order_date
          - name: total_amount
          - name: status
          - name: _fivetran_synced
          - name: _fivetran_deleted
          
      - name: products
        description: "Product catalog data"
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
          - name: product_name
          - name: category
          - name: price
          - name: _fivetran_synced
          - name: _fivetran_deleted