name: 'packleder_project'
version: '1.0.0'
config-version: 2

profile: 'packleder_azure'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  packleder_project:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      +indexes: []  # Avoid Synapse-specific syntax

vars:
  # Client identification
  client_name: 'packleder'
  
  # Database configuration - UPDATE THESE
  packleder_database: 'Packleder-DB'  # Update with actual database name
  
  # Schema mappings - UPDATE THESE based on actual schemas
  cin7_schema: 'cin7core'  # Update if different
  shopify_schema: 'shopify'  # Update if different
  xero_schema: 'xero'  # Update if different
  
  # Feature flags
  has_shopify: true
  has_xero: false  # Set to true when Xero is connected
  has_cin7: true

# dbt Cloud configuration (if using dbt Cloud)
dbt-cloud:
  project-id: # Will be populated when connected to dbt Cloud