name: 'oldschool_project'
version: '1.0.0'
config-version: 2

profile: 'oldschool'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  oldschool_project:
    staging:
      +materialized: view
      +schema: staging
      +post-hook: []
      +pre-hook: []
    intermediate:
      +materialized: view
      +schema: intermediate
      +post-hook: []
      +pre-hook: []
    marts:
      +materialized: table
      +schema: marts
      +post-hook: []
      +pre-hook: []
    marts_simple:
      +materialized: table
      +schema: marts
      +post-hook: []
      +pre-hook: []

vars:
  fivetran_database: 'OldSchool-Dev-DB'
  fivetran_schema: 'fivetran'

dbt-cloud:
  project-id: 70471823501225